# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fichardu
email: xufu90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Want to leave something.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fichardu.github.io" # the base hostname & protocol for your site
github_username:  Fichardu

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-79244019-1

theme: jekyll-theme-minimal